id: P41A5FF62
initial_creation_type: input
source_metadata:
  title: Vajrasattva Series
  language: it
  description: 'A series of texts related to the deity Vajrasattva (rdo rje sems dpa''):'
  volume:
    16e65b372c6d42f2bbff9baecf8caa39:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Confession
    d15739ead0a54d568217bc9fa171859b:
      title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
      parent: Guru Yoga
    25a5c0aadf6042988d86a7d53d5236de:
      title: 'A Shower of Great Bliss: A Lineage Prayer for the Guru Yoga based on
        Vajrasattva'
      parent: Lineage Prayers
    bf24e108ee3a4dc3af43f91be473eab2:
      title: A Method of Purifying Samaya Violations by Relying on the Glorious Guru
        Vajrasattva
      parent: Practices
    afff3cd5f6af43d69479eeb8dd7f585e:
      title: A Song of Innermost Praise to Vajrasattva
      parent: Praise
    0eb96403e7134ad399d7e7a7934119af:
      title: 'Wish-Granting Provision of Twofold Accomplishment: A Praise of Vajrasattva'
      parent: Praise
    55784aa3256141dea2ecca063df4e04a:
      title: In Praise of Glorious Vajrasattva
      parent: Praise
    9298d5a6ff0a4190af71a64c5967c52c:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    749f3eada09e4df180c3bbebaa22c7e9:
      title: Brief Vajrasattva Visualisation and Mantra Recitation
      parent: Sādhanas
    dbaf553ff25e43fea34e03e28cf6ae07:
      title: 'The Cintāmaṇi (Wish-Fulfilling Jewel) Instruction: A Sādhana of the
        Glorious Vajrasattva, a Method of Purification and Accomplishment for Both
        Self and Others'
      parent: Sādhanas
created_at: '2022-03-01T06:32:25.086060'
last_modified_at: '2022-03-01T06:32:25.086062'
